config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sorts

  resources :costs

  resources :accounts do
    collection do
      get :statistic
      get :budget
    end
  end 
  

  root 'accounts#index'

end

app/models/sort.rb
class Sort < ActiveRecord::Base
    has_many :accounts
    has_many :costs
    
    validates  :title,presence: { message: '請填寫類別' }
end

app/controllers/sorts_controller.rb
class SortsController < ApplicationController
  before_action :set_sort, only: [:show, :edit, :update, :destroy]

  # GET /sorts
  # GET /sorts.json
  def index
    @sorts = Sort.all
  end

  # GET /sorts/1
  # GET /sorts/1.json
  def show
  end

  # GET /sorts/new
  def new
    @sort = Sort.new
  end

  # GET /sorts/1/edit
  def edit
  end

  # POST /sorts
  # POST /sorts.json
  def create
    @sort = Sort.new(sort_params)

    respond_to do |format|
      if @sort.save
        format.html { redirect_to @sort, notice: 'Sort was successfully created.' }
        format.json { render :show, status: :created, location: @sort }
      else
        format.html { render :new }
        format.json { render json: @sort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sorts/1
  # PATCH/PUT /sorts/1.json
  def update
    respond_to do |format|
      if @sort.update(sort_params)
        format.html { redirect_to @sort, notice: 'Sort was successfully updated.' }
        format.json { render :show, status: :ok, location: @sort }
      else
        format.html { render :edit }
        format.json { render json: @sort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sorts/1
  # DELETE /sorts/1.json
  def destroy
    @sort.destroy
    respond_to do |format|
      format.html { redirect_to sorts_url, notice: 'Sort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sort
      @sort = Sort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sort_params
      params.require(:sort).permit(:title)
    end
end

app/helpers/sorts_helper.rb
module SortsHelper
end

app/views/sorts/_form.html.erb
<div class="form">
<%= simple_form_for (@sort) do |f| %>
  <% if @sort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sort.errors.count, "error") %> prohibited this sort from being saved:</h2>

      <ul>
      <% @sort.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= link_to '返回', sorts_path ,class:'btn btn-link btn-lg'%>
    <%= f.submit "新增/更新" ,class:'btn btn-link btn-lg'%>
  </div>
  <div class="field">
    <%= f.input :title ,label:"類別名稱：" %>
  </div>

<% end %>
</div>

app/views/sorts/edit.html.erb
<h1>Editing Sort</h1>

<%= render 'form' %>

<%= link_to 'Show', @sort %> |
<%= link_to 'Back', sorts_path %>

app/views/sorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>類別</h1>
<%= link_to '返回首頁', accounts_path ,class:'btn btn-link btn-lg'%>|
<%= link_to '新增類別', new_sort_path ,class:'btn btn-link btn-lg'%>
<table  class="table table-hover">
  <thead>
    <tr>
      <th>類別名稱</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sorts.each do |sort| %>
      <tr>
        
        <td><%= link_to sort.title, sort %></td>
        <td><%= link_to 'Edit', edit_sort_path(sort) ,class:'btn btn-warning'%></td>
        <td><%= link_to 'Destroy', sort, method: :delete, data: { confirm: 'Are you sure?' } ,class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sorts/new.html.erb
<h1>新增類別</h1>

<%= render 'form' %>

app/views/sorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sort name:</strong>
  <%= @sort.title %>
</p>

<%= link_to 'Edit', edit_sort_path(@sort) %> |
<%= link_to 'Back', sorts_path %>