config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sorts

  resources :costs

  resources :accounts do
    collection do
      get :statistic
      get :budget
    end
  end 
  

  root 'accounts#index'

end

app/models/cost.rb
class Cost < ActiveRecord::Base
    belongs_to :sort
    
    validates  :cost_name, presence: { message: '請填寫預算名稱' }
    validates  :cost_price , presence: { message: '請填寫金額量' }
    validates  :sort_id ,presence: { message: '請填寫要預算的類別' }
    validates  :start_time ,presence: { message: '請填寫開始日期' }
    validates  :end_time,presence: { message: '請填寫結束日期' }
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all.order('start_time ,end_time asc')
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:cost_name, :cost_price, :start_time, :end_time, :sort_id)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<div class="form">
<%= simple_form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    
    <%= link_to '返回', costs_path ,class:'btn btn-link btn-lg'%>
    <%= f.submit "新增/更新" ,class:'btn btn-link btn-lg'%>
  </div>
  <div class="field">
    
    <%= f.input :cost_name, label:'預算名稱：' %>
    </br>
    
    <%= f.input :start_time, as: :date,:input_html => { :value => Date.today}, html5: true, label: "起始日：" %></br>
    <%= f.input :end_time, as: :date,:input_html => { :value => Date.today}, html5: true, label: "結束日：" %></br>
	  
    <%= f.input :cost_price ,label:"金額：" %>
    </br>
    
    <%= f.association :sort, label:'類別：' %>
  </div>
  
  
  
<% end %>
</div>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>預算</h1>
<%= link_to '返回預算規劃', budget_accounts_path ,class:'btn btn-link btn-lg'%>|
<%= link_to '新增預算', new_cost_path ,class:'btn btn-link btn-lg'%>

<table  class="table table-hover">
  <thead>
    <tr>
      <th>預算名稱</th>
      <th>起始日</th>
      <th>結束日</th>
      <th>金額</th>
      <th>類別</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= link_to cost.cost_name , cost %></td>
        <td><%= cost.start_time %></td>
        <td><%= cost.end_time %></td>
        <td><%= cost.cost_price %></td>
        <td><%= cost.sort.try(:title) %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) ,class:'btn btn-warning'%></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/costs/new.html.erb
<h1>新增預算</h1>

<%= render 'form' %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost name:</strong>
  <%= @cost.cost_name %>
</p>

<p>
  <strong>起始日:</strong>
  <%= @cost.start_time %>
</p>

<p>
  <strong>結束日:</strong>
  <%= @cost.end_time %>
</p>

<p>
  <strong>金額:</strong>
  <%= @cost.cost_price %>
</p>

<p>
  <strong>類別:</strong>
  <%= @cost.sort.try(:title) %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>