config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sorts

  resources :costs

  resources :accounts do
    collection do
      get :statistic
      get :budget
    end
  end 
  

  root 'accounts#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
    belongs_to :sort
    
    validates  :name,presence: { message: '請填寫商品名' }
    validates  :buy_price, presence: { message: '請填寫價格' }
    validates  :num , presence: { message: '請填寫數量' }
    validates  :buy_date ,presence: { message: '請填寫購買日期' }
    validates  :buy_store ,presence: { message: '請填寫購買商店' }
    validates  :sort_id,presence: { message: '請填寫購買類別' }
    # validates  :buy_price, :num ,numericality: true
    # searchable do
    #     text :name, :buy_store
    # end
    
    def self.total_on(date)
        where("date(buy_date) = ?" , date).sum(:buy_price)
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [ :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  
  def index
    @accounts = Account.all
    @costs =Cost.all.order('start_time ,end_time asc')
    @grouped_months = @accounts.group_by { |r| r.buy_date.beginning_of_month}
    
    if params[:search]
        @accounts = Account.order('buy_date asc').where('name LIKE ? OR title LIKE ? OR buy_store LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%").joins(:sort)
    else
        @accounts = Account.all.order('buy_date asc')
    end
    
    # @search = Account.search do
    #   fulltext params[:search]
    # end
    # @accounts = @search.results
  end
  
  def budget
    @accounts = Account.all
    @costs =Cost.all.order('start_time ,end_time asc')
    @grouped_months = @accounts.group_by { |r| r.buy_date.beginning_of_month}
    @puts=['01','02','03','04','05','06','07','08','09','10','11','12']
    @month_total=[]
    @month_cost=[]
    @month_breakfast_total=[]
    @month_lunch_total=[]
    @month_dinner_total=[]
    @month_drink_total=[]
    
    @year=Time.now.year.to_s
    @month=Time.now.month
    
    (0..11).each do |i|
      @month_total[i] = Account.where(['buy_date between ? and ?','2015-'+ @puts[i] +'-01','2015-'+ @puts[i] +'-31']).sum(:buy_price)
      
      @month_cost[i] = Cost.where(['start_time between ? and ? and end_time between ? and ?','2015-'+ @puts[i] +'-01','2015-'+ @puts[i] +'-31','2015-'+ @puts[i] +'-01','2015-'+ @puts[i] +'-31']).order('start_time desc')
      
      @month_breakfast_total[i] = Account.where('buy_date between ? and ? and title=?','2015-'+ @puts[i] +'-01','2015-'+ @puts[i] +'-31',"早餐").joins(:sort).sum(:buy_price)
      @month_lunch_total[i] = Account.where(['buy_date between ? and ? and title=?','2015-'+ @puts[i] +'-01','2015-'+ @puts[i] +'-31',"午餐"]).joins(:sort).sum(:buy_price)
      @month_dinner_total[i] = Account.where(['buy_date between ? and ? and title=?','2015-'+ @puts[i] +'-01','2015-'+ @puts[i] +'-31',"晚餐"]).joins(:sort).sum(:buy_price)
      @month_drink_total[i] = Account.where(['buy_date between ? and ? and title=?','2015-'+ @puts[i] +'-01','2015-'+ @puts[i] +'-31',"飲料"]).joins(:sort).sum(:buy_price)
    end
    
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end
  
  def statistic
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :buy_price, :num, :buy_date, :buy_store, :sort_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="form">
<%= simple_form_for (@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
   <div class="actions">
    <%= link_to "返回首頁", accounts_path, class:'btn btn-link btn-lg' %>|
    <%= f.submit "新增/更新" ,class:'btn btn-link btn-lg'%>
    
  </div>

  <div class="field">
    
    <%= f.input :buy_date, as: :date ,:input_html => { :value => Date.today}, html5: true, label: "購買日期：" %></br>
	  
    <%= f.input :name, label:'項目：' %></br>
    
    <%= f.input :num ,label:"數量：" %></br>
    
    <%= f.input :buy_price ,label:"金額：" %></br>
    
    <%= f.input :buy_store ,label:"購賣商家：" %></br>
    
    <%= f.association :sort, label:'購買類別：' %>
  </div>
  
  
<% end %>
</div>

app/views/accounts/budget.html.erb
<h1>本月預算</h1>
<%= link_to '返回首頁', accounts_path ,class:'btn btn-link btn-lg'%>|
<%= link_to '新增預算', costs_path ,class:'btn btn-link  btn-lg'%>
<h3><%= @month %>月，總共花了<%= @month_total[@month-1] %>元，預算為</h3>
<table class="table table-hover">
<thead>
  <tr>
    <th>類別</th>
    <th>起始日</th>
    <th>結束日</th>
    <th>預算金額</th>
    <th>剩餘金額</th>
  </tr>
</thead>
  <% @month_cost[@month-1].each do |month_cost| %>
    <tr>
        <td><%= month_cost.sort.try(:title) %></td>
        <td><%= month_cost.start_time %></td>
        <td><%= month_cost.end_time %></td>
        <td><%= month_cost.cost_price %></td>
        <td>
          <% if  month_cost.sort.try(:title)=="早餐"%>
            <%= month_cost.cost_price-@month_breakfast_total[@month-1]%>
          <% elsif   month_cost.sort.try(:title)=="午餐"%>
            <%= month_cost.cost_price-@month_lunch_total[@month-1]%>
          <% elsif   month_cost.sort.try(:title)=="晚餐"%>
            <%= month_cost.cost_price-@month_dinner_total[@month-1]%>
          <% else %>
            <%= month_cost.cost_price-@month_drink_total[@month-1]%>
          <% end %>
        </td>
    </tr>
  <% end %>
</table>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account,class:'btn btn-default' %> |
<%= link_to 'Back', accounts_path,class:'btn btn-default'%>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Money</h1>
<%= link_to '新增類別', sorts_path ,class:'btn btn-link btn-lg'%>|
<%= link_to '新增帳目', new_account_path ,class:'btn btn-link btn-lg'%>|
<%= link_to '預算規劃', budget_accounts_path ,class:'btn btn-link btn-lg'%> | 
<%= link_to '統計資料', statistic_accounts_path ,class:'btn btn-link btn-lg'%>
</br>

</br>
<%= form_tag accounts_path, method: :get do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
    <%= submit_tag "搜尋", name: nil %>
<% end %>

<br/>
<br/>
<%= link_to '顯示全部', accounts_path ,class:'btn btn btn-info'%>
<br/>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>日期</th>
        <th>項目</th>
        <th>數量</th>
        <th>金額</th>
        <th>購賣商家</th>
        <th>購買類別</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    
      <% @accounts.each do |account| %>
      <tr>
        <td><%= account.buy_date %></td>
        <td><%= link_to account.name ,account %></td>
        <td><%= account.num %></td>
        <td><%= account.buy_price %></td>
        <td><%= account.buy_store %></td>
        <td><%= account.sort.try(:title) %></td>
        
        <td><%= link_to 'Edit', edit_account_path(account) ,class:'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } ,class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </table>

app/views/accounts/new.html.erb
<h1>新增帳目</h1>

<%= render 'form' %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Buy date:</strong>
  <%= @account.buy_date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Num:</strong>
  <%= @account.num %>
</p>

<p>
  <strong>Buy price:</strong>
  <%= @account.buy_price %>
</p>

<p>
  <strong>Buy store:</strong>
  <%= @account.buy_store %>
</p>

<p>
  <strong>Store:</strong>
  <%= @account.sort.try(:title) %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/statistic.html.erb
<script type="text/javascript" charset="utf-8">
  $(function() {
    new Highcharts.Chart({
      chart: {
        renderTo: "accounts_chart",
        backgroundColor: '#CCEEFF',
        type: 'line'
      },
      title: {
        text: "Accounts by Cost"
      },
      xAxis: {
        type: "datetime"
        
      },
      yAxis: {
        min: 0,
        lineColor: '#000088',
        title: {
          text: "Dollars"
        }
      },
      tooltip: {
        formatter: function() {
          return Highcharts.dateFormat("%B %e, %Y", this.x) + ': ' +
            "$" + Highcharts.numberFormat(this.y, 2);
        }
      },
      plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: true
            }
        },
      series: [{
        pointInterval: <%= 1.day * 1000 %>, //24 * 3600 * 1000
        pointStart: <%= 4.weeks.ago.to_i * 1000 %>,
        data: <%= (4.weeks.ago.to_date..Date.today).map { |date|Account.total_on(date).to_f  }.inspect %>,
        type: 'area'
      }]
    });
  });
</script>
<h1>本月支出統計</h1>
<%= link_to '返回首頁', accounts_path ,class:'btn btn-link btn-lg'%>|
<%= link_to '新增類別', sorts_path ,class:'btn btn-link  btn-lg'%>| 
<%= link_to '預算規劃', budget_accounts_path ,class:'btn btn-link  btn-lg'%>| 
<%= link_to '新增帳目', new_account_path ,class:'btn btn-link btn-lg'%> 

<div id="accounts_chart" style="width:600px; height:300px;"></div>